[tool.poetry]
name = "tweede-kamer"
version = "0.1.0"
description = ""
authors = ["David Wild <david_wild@gmx.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
jupyter = "^1.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
